###
POST http://localhost:1234/user/register
content-type: application/json

{
  "name": "Nacho",
  "username": "nacho",
  "email": "nacho@email.es",
  "confirmEmail": "nacho@email.es",
  "password": "123456",
  "confirmPassword": "123456",
  "profile": "personal"
}

###
POST http://localhost:1234/user/register
content-type: application/json

{
  "name": "Test",
  "username": "test",
  "email": "test@email.es",
  "confirmEmail": "test@email.es",
  "password": "123456",
  "confirmPassword": "123456",
  "profile": "profesional",
  "address": {
    "street": "calle",
    "city": "Ciudad",
    "zipCode": 10000,
    "country": "spain"
  }
}

###
POST http://localhost:1234/user/login
content-type: application/json

{
  "input": "nacho@email.es",
  "password": "123456"
}

###
POST http://localhost:1234/user/login
content-type: application/json

{
  "input": "test",
  "password": "123456"
}