###
POST http://localhost:1234/user/register
content-type: application/json

{
  "name": "Nacho",
  "username": "nacho",
  "email": "nacho@email.es",
  "confirmEmail": "nacho@email.es",
  "password": "123456",
  "confirmPassword": "123456",
  "profile": "personal"
}

###
POST http://localhost:1234/user/register
content-type: application/json

{
  "name": "Test",
  "username": "test",
  "email": "test@email.es",
  "confirmEmail": "test@email.es",
  "password": "123456",
  "confirmPassword": "123456",
  "profile": "profesional",
  "address": {
    "street": "calle",
    "city": "Ciudad",
    "zipCode": 10000,
    "country": "spain"
  }
}

###
POST http://localhost:1234/user/login
content-type: application/json

{
  "input": "nacho@email.es",
  "password": "123456"
}

###
POST http://localhost:1234/user/login
content-type: application/json

{
  "input": "test",
  "password": "123456"
}


### Crear un nuevo post ###
POST http://localhost:1234/posts
Content-Type: application/json

{
    "title": "Nuevo post",
    "content": "Contenido del nuevo post"
}

### Obtener todos los posts ###
GET http://localhost:1234/posts
### Obtener un post por su ID ###
# GET http://localhost:1234/posts/:id
GET http://localhost:1234/posts/6522ef6112905e1a42c1e2ec

### Actualizar un post por su ID ###
# PUT http://localhost:1234/posts/:id
PUT http://localhost:1234/posts/6522ef6112905e1a42c1e2ec

Content-Type: application/json

{
    "title": "Título actualizado",
    "content": "Contenido actualizado"
}

### Eliminar un post por su ID ###
# DELETE http://localhost:1234/posts/:id
DELETE http://localhost:1234/posts/6522ef6112905e1a42c1e2ec

