###
POST http://localhost:1234/api/messages
content-type: application/json

{
  "recipientId": "65303e9f97378e1fe910b74c",
  "message": "Mensaje desde el otro lado"
}

###
GET http://localhost:1234/api/messages/6531074b97863b7b6b1476a8

###
GET http://localhost:1234/api/messages/conversations

###
GET http://localhost:1234/api/messages/conversation/6567ad6c90307d2a4955713a

###
POST http://localhost:1234/api/messages/new
content-type: application/json

{
  "recipientId": "65633be0cdbbec4fad2383ef"
}