### Obtener un post por su ID 
GET http://localhost:1234/api/posts/652edb68a299150a6dbf2008

### Obtener feed
GET http://localhost:1234/api/posts/feed

### Obtener post de un usuario
GET http://localhost:1234/api/posts/user/test

### Crear un nuevo post
POST http://localhost:1234/api/posts/create
Content-Type: application/json

{
    "author": "652eda0aa299150a6dbf1fef",
    "content": "Post de prueba 1"
}

### Actualizar un post por su ID
PATCH http://localhost:1234/api/posts/652edb68a299150a6dbf2008
Content-Type: application/json

{
    "content": "Contenido actualizado"
}

### Eliminar un post por su ID
DELETE http://localhost:1234/api/posts/delete/652e5ee159f46d0599871f18

### Fav / Unfav un post
POST http://localhost:1234/api/posts/fav/652edb68a299150a6dbf2008

### Responder un post
POST http://localhost:1234/api/posts/reply/652edb68a299150a6dbf2008
Content-Type: application/json

{
    "text": "Esta es una respuesta"
}