### Get post by the ID 
GET http://localhost:1234/api/posts/652edb68a299150a6dbf2008

### Get user feed
GET http://localhost:1234/api/posts/feed

### Get all posts by username
GET http://localhost:1234/api/posts/user/test

### Create new post
POST http://localhost:1234/api/posts/create
Content-Type: application/json

{
    "author": "6532a892929368a1d583aea2",
    "content": "Post de prueba 2"
}

### Update a post
PATCH http://localhost:1234/api/posts/652edb68a299150a6dbf2008
Content-Type: application/json

{
    "content": "Contenido actualizado"
}

### Delete a post
DELETE http://localhost:1234/api/posts/delete/652e5ee159f46d0599871f18

### Fav / Unfav post
POST http://localhost:1234/api/posts/fav/652edb68a299150a6dbf2008

### Reply post
POST http://localhost:1234/api/posts/reply/652edb68a299150a6dbf2008
Content-Type: application/json

{
    "text": "Esta es una respuesta"
}