###
POST http://localhost:1234/api/users/register
content-type: application/json

{
  "name": "Nacho",
  "username": "nacho",
  "email": "nacho@email.es",
  "password": "123456",
  "confirmPassword": "123456",
  "profile": "personal"
}

###
POST http://localhost:1234/api/users/register
content-type: application/json

{
  "name": "Test",
  "username": "test",
  "email": "test@email.es",
  "password": "123456",
  "confirmPassword": "123456",
  "profile": "profesional",
  "address": {
    "street": "calle",
    "city": "Ciudad",
    "zipCode": 10000,
    "country": "spain"
  }
}

###
POST http://localhost:1234/api/users/login
content-type: application/json

{
  "input": "nacho@email.es",
  "password": "123456"
}

###
POST http://localhost:1234/api/users/login
content-type: application/json

{
  "input": "test",
  "password": "123456"
}

###
POST http://localhost:1234/api/users/logout

###
POST http://localhost:1234/api/users/follow/652e6fc8939b0e5a6c80b8d6

###
PATCH http://localhost:1234/api/users/update/652db234b3d826d8fab82138
content-type: application/json

{
  "name": "Nacho",
  "username": "nacho",
  "password": "123456",
  "newPassword": "123456",
  "confirmNewPassword": "123456",
  "email": "nacho@email.es",
  "profile": "personal"
}

###
GET http://localhost:1234/api/users/profile/nacho

###
DELETE http://localhost:1234/api/users/delete/652db54a61d352777ee1f54c
content-type: application/json
