### Register user with 'personal' profile
POST http://localhost:1234/api/users/register
content-type: application/json

{
  "name": "shauny",
  "username": "shauny",
  "email": "shauny@email.es",
  "password": "123456",
  "confirmPassword": "123456",
  "profile": "personal"
}

### Register user with 'profesional' profile
POST http://localhost:1234/api/users/register
content-type: application/json

{
  "name": "Test",
  "username": "test",
  "email": "test@email.es",
  "password": "123456",
  "confirmPassword": "123456",
  "profile": "profesional",
  "address": {
    "street": "calle",
    "city": "Ciudad",
    "zipCode": 10000,
    "country": "spain"
  }
}

### Login user with 'personal' profile
POST http://localhost:1234/api/users/login
content-type: application/json

{
  "input": "shauny@email.es",
  "password": "123456"
}

### Login user with 'profesional' profile
POST http://localhost:1234/api/users/login
content-type: application/json

{
  "input": "test",
  "password": "123456"
}

### Logout
POST http://localhost:1234/api/users/logout

### Follow user
POST http://localhost:1234/api/users/follow/652faca5a63a1e87d8ed0a55

### Update user
PATCH http://localhost:1234/api/users/update/65380d33574583bcaad83f9c
content-type: application/json

{
  "name": "shauny",
  "username": "nacho",
  "password": "123456",
  "newPassword": "123456",
  "confirmNewPassword": "123456",
  "email": "shauny@email.es",
  "profile": "personal"
}

### Get user information
GET http://localhost:1234/api/users/profile/nacho

### Delete user
DELETE http://localhost:1234/api/users/delete/652db54a61d352777ee1f54c
content-type: application/json
